# Generated by Django 3.2.7 on 2021-09-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210919_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/profile-small-1.jpg', upload_to='images'),
        ),
    ]
