# Generated by Django 3.2.7 on 2021-09-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210922_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile-small-15.jpg', null=True, upload_to='images'),
        ),
    ]
